const arr = [
  {
    display: "table-header-group",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-table-thead",
  },
  {
    display: "table",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "",
  },
  {
    display: "block",
    position: "sticky",
    overflow: "hidden",
    overflowX: "hidden",
    overflowY: "hidden",
    className: "ant-table-header ant-table-sticky-holder",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-table-container",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-table ant-table-middle ant-table-scroll-horizontal",
  },
  {
    display: "block",
    position: "relative",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-spin-container",
  },
  {
    display: "block",
    position: "relative",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-spin-nested-loading css-dev-only-do-not-override-ixblex",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-table-wrapper css-dev-only-do-not-override-ixblex",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-pro-card-body css-dev-only-do-not-override-9lt2z8",
  },
  {
    display: "flex",
    position: "relative",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-pro-card css-dev-only-do-not-override-9lt2z8",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-pro-table css-dev-only-do-not-override-9lt2z8",
  },
  {
    display: "table-cell",
    position: "relative",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-table-cell",
  },
  {
    display: "table-row",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-table-expanded-row ant-table-expanded-row-level-1",
  },
  {
    display: "table-row-group",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-table-tbody",
  },
  {
    display: "table",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "",
  },
  {
    display: "block",
    position: "static",
    overflow: "auto hidden",
    overflowX: "auto",
    overflowY: "hidden",
    className: "ant-table-body",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-table-container",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-table ant-table-middle ant-table-scroll-horizontal",
  },
  {
    display: "block",
    position: "relative",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-spin-container",
  },
  {
    display: "block",
    position: "relative",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-spin-nested-loading css-dev-only-do-not-override-ixblex",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-table-wrapper css-dev-only-do-not-override-ixblex",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-pro-card-body css-dev-only-do-not-override-9lt2z8",
  },
  {
    display: "flex",
    position: "relative",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-pro-card css-dev-only-do-not-override-9lt2z8",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-pro-table css-dev-only-do-not-override-9lt2z8",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-pro css-dev-only-do-not-override-9lt2z8",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-card-body",
  },
  {
    display: "block",
    position: "relative",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "ant-card ant-card-bordered css-dev-only-do-not-override-ixblex",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "pt-5 lg:pl-2 xl:ml-0 xl:max-w-none",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "xl:pl-[14rem]",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "max-w-8xl lg:px-8lg:pl-[19.5rem] mx-auto px-4 sm:px-6",
  },
  {
    display: "block",
    position: "relative",
    overflow: "hidden auto",
    overflowX: "hidden",
    overflowY: "auto",
    className: "relative h-screen overflow-hidden overflow-y-auto",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "bg-gray-100",
  },
  {
    display: "block",
    position: "static",
    overflow: "visible",
    overflowX: "visible",
    overflowY: "visible",
    className: "",
  },
];
